import type { FaColumnDef } from './faColumnLayout'

/** Catalog + default layout for allocation editor grid. Runtime editors stay in FixedAssetAllocationColumns. */
export const FIXED_ASSET_ALLOCATION_COLUMN_DEFS: readonly FaColumnDef[] = [
  {
    fieldName: 'ROW_KEY',
    captionKey: 'ROW_KEY',
    captionFallback: 'ROW_KEY',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'ALLOC_ID',
    captionKey: 'ALLOC_ID',
    captionFallback: 'ALLOC_ID',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'COMPANY_CD',
    captionKey: 'COMPANY_CD',
    captionFallback: 'Company',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'ASSET_ID',
    captionKey: 'ASSET_ID',
    captionFallback: 'Asset ID',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'DEPARTMENT_ID',
    captionKey: 'DEPARTMENT_ID',
    captionFallback: 'DEPARTMENT_ID',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'DEP_NAME_VIET',
    captionKey: 'DEP_NAME_VIET',
    captionFallback: 'DEP_NAME_VIET',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'DEP_NAME_ENG',
    captionKey: 'DEP_NAME_ENG',
    captionFallback: 'DEP_NAME_ENG',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'DEP_NAME_KOR',
    captionKey: 'DEP_NAME_KOR',
    captionFallback: 'DEP_NAME_KOR',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'DEP_NAME_CHINA',
    captionKey: 'DEP_NAME_CHINA',
    captionFallback: 'DEP_NAME_CHINA',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'DEBIT_ACCT_ID',
    captionKey: 'DEBIT_ACCT_ID',
    captionFallback: 'DEBIT_ACCT_ID',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'DEBIT_ACCT_NM_ENG',
    captionKey: 'DEBIT_ACCT_NM_ENG',
    captionFallback: 'DEBIT_ACCT_NM_ENG',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'DEBIT_ACCT_NM_KOR',
    captionKey: 'DEBIT_ACCT_NM_KOR',
    captionFallback: 'DEBIT_ACCT_NM_KOR',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'DEBIT_ACCT_NM_CHINA',
    captionKey: 'DEBIT_ACCT_NM_CHINA',
    captionFallback: 'DEBIT_ACCT_NM_CHINA',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'CREDIT_ACCT_ID',
    captionKey: 'CREDIT_ACCT_ID',
    captionFallback: 'CREDIT_ACCT_ID',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'CREDIT_ACCT_NM_ENG',
    captionKey: 'CREDIT_ACCT_NM_ENG',
    captionFallback: 'CREDIT_ACCT_NM_ENG',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'CREDIT_ACCT_NM_KOR',
    captionKey: 'CREDIT_ACCT_NM_KOR',
    captionFallback: 'CREDIT_ACCT_NM_KOR',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'CREDIT_ACCT_NM_CHINA',
    captionKey: 'CREDIT_ACCT_NM_CHINA',
    captionFallback: 'CREDIT_ACCT_NM_CHINA',
    defaultVisible: false,
    locked: true,
  },
  {
    fieldName: 'ALLOC_SEQ',
    captionKey: 'ALLOC_SEQ',
    captionFallback: 'STT',
    defaultVisible: true,
    defaultWidth: 70,
    allowEditing: false,
  },
  {
    fieldName: 'ALLOC_TYPE',
    captionKey: 'ALLOC_TYPE',
    captionFallback: 'Kiểu phân bổ',
    defaultVisible: true,
    defaultWidth: 120,
  },
  {
    fieldName: 'ALLOC_RATE',
    captionKey: 'ALLOC_RATE',
    captionFallback: 'Tỷ lệ %',
    defaultVisible: true,
    defaultWidth: 110,
    dataType: 'number',
    format: '#,##0.####',
  },
  {
    fieldName: 'FIRST_ALLOC_AMT',
    captionKey: 'FIRST_ALLOC_AMT',
    captionFallback: 'Tiền đầu',
    defaultVisible: true,
    defaultWidth: 120,
    dataType: 'number',
    format: '#,##0.##',
  },
  {
    fieldName: 'NORMAL_ALLOC_AMT',
    captionKey: 'NORMAL_ALLOC_AMT',
    captionFallback: 'Tiền giữa',
    defaultVisible: true,
    defaultWidth: 120,
    dataType: 'number',
    format: '#,##0.##',
  },
  {
    fieldName: 'LAST_ALLOC_AMT',
    captionKey: 'LAST_ALLOC_AMT',
    captionFallback: 'Tiền cuối',
    defaultVisible: true,
    defaultWidth: 120,
    dataType: 'number',
    format: '#,##0.##',
  },
  {
    fieldName: 'DEBIT_ACCT_CD',
    captionKey: 'DEBIT',
    captionFallback: 'TK Nợ',
    defaultVisible: true,
  },
  {
    fieldName: 'DEBIT_ACCT_NM_VIET',
    captionKey: 'ACC_NM_DEBIT',
    captionFallback: 'Tên TK Nợ',
    defaultVisible: false,
  },
  {
    fieldName: 'CREDIT_ACCT_CD',
    captionKey: 'CREDIT',
    captionFallback: 'TK Có',
    defaultVisible: true,
  },
  {
    fieldName: 'CREDIT_ACCT_NM_VIET',
    captionKey: 'ACC_NM_CREDIT',
    captionFallback: 'Tên TK Có',
    defaultVisible: false,
  },
  {
    fieldName: 'DEPARTMENT_CD',
    captionKey: 'DEPARTMENT_CD',
    captionFallback: 'Bộ phận',
    defaultVisible: true,
    defaultWidth: 220,
  },
  {
    fieldName: 'NOTE',
    captionKey: 'NOTE',
    captionFallback: 'Ghi chú',
    defaultVisible: true,
    minWidth: 140,
  },
]
