export const SHORTCUT_KEYS = {
  NEW_OR_ADD_RECEIPT: "mod+1",
  ADD_PAYMENT: "mod+2",
  OPEN: "mod+o",
  EDIT: "mod+e",
  DELETE: "mod+d",
  POST: "mod+g",
  UNPOST: "mod+b",
  QUICK_SEARCH: "alt+x",
  ADVANCED_VOUCHER_SEARCH: "alt+y",
  SAVE: "mod+s",
  SAVE_AND_NEW: "mod+shift+s",
  SAVE_AND_CLOSE: "mod+q",
  SAVE_AND_PRINT: "mod+alt+p",
  SAVE_AND_RELEASE: "mod+alt+r",
  PRINT: "mod+p",
  UTILITIES: "mod+m",
  HOLD: "mod+u",
  VIEW_PREVIOUS_DAY_VOUCHER: "alt+b",
  VIEW_NEXT_DAY_VOUCHER: "alt+n",
  DUPLICATE: "mod+shift+c",
  ADD_ROW: "ctrl+insert",
  DELETE_ROW: "ctrl+delete",
  QUICK_ADD_MASTER_DATA: "f9",
  SWITCH_TAB_OUTSIDE_LIST: "alt+tab",
  SWITCH_TAB_IN_DETAIL: "alt+tab",
  COPY_VALUES_DOWN: "ctrl+2",
  QUICK_ITEM_SEARCH: "f3",
  INPUT_DETAIL_BY_SPEC_CODE: "f6",
  VIEW_INVENTORY_BALANCE: "ctrl+f2",
  SELECT_ISSUE_VOUCHER_SPECIFIC_IDENTIFICATION: "f8",
  VIEW_ACCOUNT_BALANCE: "ctrl+3",
  RECALCULATE_AMOUNT_BY_AFTER_TAX_PRICE: "ctrl+4",
  CREATE_PURCHASE_FROM_EINVOICE: "ctrl+i",
  IMPORT: "alt+i",
  EXPORT_EXCEL: "alt+e",
  EXPORT_PDF: "alt+p",
  COLUMN_CHOOSER: "alt+l",
  HELP: "f1",
  CLOSE: "escape",
  REFRESH: "f5",
  FOCUS_MENU_SEARCH: "mod+k",
} as const

export type ShortcutKeyCombo = (typeof SHORTCUT_KEYS)[keyof typeof SHORTCUT_KEYS]
