import type { ColumnConfig } from "@/types/table";

export const receiptColumns: ColumnConfig[] = [
  {
    id: "receiptNo",
    dataField: "receiptNo",
    displayName: "Số chứng từ",
    width: 130,
    visible: true,
    pinned: false,
    originalOrder: 0,
  },
  {
    id: "transactionDate",
    dataField: "transactionDate",
    displayName: "Ngày giao dịch",
    width: 130,
    visible: true,
    pinned: false,
    originalOrder: 1,
  },
  {
    id: "amount",
    dataField: "amount",
    displayName: "Số tiền",
    width: 130,
    visible: true,
    pinned: false,
    originalOrder: 2,
  },
  {
    id: "description1",
    dataField: "description1",
    displayName: "Mô tả 1",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 3,
  },
  {
    id: "description2",
    dataField: "description2",
    displayName: "Mô tả 2",
    width: 200,
    visible: false,
    pinned: false,
    originalOrder: 4,
  },
  {
    id: "receiverName",
    dataField: "receiverName",
    displayName: "Người nhận tiền",
    width: 160,
    visible: true,
    pinned: false,
    originalOrder: 5,
  },
  {
    id: "modifiedDate",
    dataField: "modifiedDate",
    displayName: "Ngày sửa đổi",
    width: 130,
    visible: true,
    pinned: false,
    originalOrder: 6,
  },
  {
    id: "isLocked",
    dataField: "isLocked",
    displayName: "Đã khóa",
    width: 100,
    visible: true,
    pinned: false,
    originalOrder: 7,
  },
  {
    id: "email",
    dataField: "email",
    displayName: "Email",
    width: 180,
    visible: true,
    pinned: false,
    originalOrder: 8,
  },
  {
    id: "attachment",
    dataField: "attachment",
    displayName: "File đính kèm",
    width: 150,
    visible: true,
    pinned: false,
    originalOrder: 9,
  },
  {
    id: "createdBy",
    dataField: "createdBy",
    displayName: "Người tạo",
    width: 130,
    visible: true,
    pinned: false,
    originalOrder: 10,
  },
  {
    id: "currentEditor",
    dataField: "currentEditor",
    displayName: "Người sửa đổi hiện tại",
    width: 150,
    visible: true,
    pinned: false,
    originalOrder: 11,
  },
  {
    id: "costCenter1",
    dataField: "costCenter1",
    displayName: "Đối tượng tập hợp chi phí 1",
    width: 180,
    visible: false,
    pinned: false,
    originalOrder: 12,
  },
  {
    id: "costCenter2",
    dataField: "costCenter2",
    displayName: "Đối tượng tập hợp chi phí 2",
    width: 180,
    visible: false,
    pinned: false,
    originalOrder: 13,
  },
  {
    id: "debit",
    dataField: "debit",
    displayName: "Nợ",
    width: 100,
    visible: false,
    pinned: false,
    originalOrder: 14,
  },
  {
    id: "debitAccountName",
    dataField: "debitAccountName",
    displayName: "Tên tài khoản nợ",
    width: 150,
    visible: false,
    pinned: false,
    originalOrder: 15,
  },
  {
    id: "credit",
    dataField: "credit",
    displayName: "Có",
    width: 100,
    visible: false,
    pinned: false,
    originalOrder: 16,
  },
  {
    id: "creditAccountName",
    dataField: "creditAccountName",
    displayName: "Tên tài khoản có",
    width: 150,
    visible: false,
    pinned: false,
    originalOrder: 17,
  },
  {
    id: "amountSecond",
    dataField: "amountSecond",
    displayName: "Số tiền (2)",
    width: 130,
    visible: false,
    pinned: false,
    originalOrder: 18,
  },
  {
    id: "fcAmount",
    dataField: "fcAmount",
    displayName: "FC Số tiền",
    width: 130,
    visible: false,
    pinned: false,
    originalOrder: 19,
  },
  {
    id: "country",
    dataField: "country",
    displayName: "Quốc gia",
    width: 130,
    visible: false,
    pinned: false,
    originalOrder: 20,
  },
  {
    id: "customerCode",
    dataField: "customerCode",
    displayName: "Mã khách hàng",
    width: 130,
    visible: false,
    pinned: false,
    originalOrder: 21,
  },
  {
    id: "customerName",
    dataField: "customerName",
    displayName: "Tên khách hàng",
    width: 150,
    visible: false,
    pinned: false,
    originalOrder: 22,
  },
  {
    id: "bankName",
    dataField: "bankName",
    displayName: "Tên ngân hàng",
    width: 150,
    visible: false,
    pinned: false,
    originalOrder: 23,
  },
  {
    id: "manageCode",
    dataField: "manageCode",
    displayName: "Mã số quản lý",
    width: 130,
    visible: false,
    pinned: false,
    originalOrder: 24,
  },
  {
    id: "manageCode2",
    dataField: "manageCode2",
    displayName: "Mã số quản lý 2",
    width: 130,
    visible: false,
    pinned: false,
    originalOrder: 25,
  },
  {
    id: "note1",
    dataField: "note1",
    displayName: "Quản lý ghi chú 1",
    width: 160,
    visible: false,
    pinned: false,
    originalOrder: 26,
  },
  {
    id: "note2",
    dataField: "note2",
    displayName: "Quản lý ghi chú 2",
    width: 160,
    visible: false,
    pinned: false,
    originalOrder: 27,
  },
  {
    id: "inventory",
    dataField: "inventory",
    displayName: "Hàng tồn kho",
    width: 130,
    visible: false,
    pinned: false,
    originalOrder: 28,
  },
];
