import { SHORTCUT_KEYS, type ShortcutKeyCombo } from "./shortcutKeys"

export const SHORTCUT_ACTIONS = {
  NEW_OR_ADD_RECEIPT: "voucher.new_or_add_receipt",
  ADD_PAYMENT: "voucher.add_payment",
  OPEN: "record.open",
  EDIT: "record.edit",
  DELETE: "record.delete",
  POST: "voucher.post",
  UNPOST: "voucher.unpost",
  QUICK_SEARCH: "navigation.quick_search",
  ADVANCED_VOUCHER_SEARCH: "voucher.advanced_search",
  SAVE: "form.save",
  SAVE_AND_NEW: "form.save_and_new",
  SAVE_AND_CLOSE: "form.save_and_close",
  SAVE_AND_PRINT: "form.save_and_print",
  SAVE_AND_RELEASE: "form.save_and_release",
  PRINT: "record.print",
  UTILITIES: "form.utilities",
  HOLD: "form.hold",
  VIEW_PREVIOUS_DAY_VOUCHER: "voucher.view_previous_day",
  VIEW_NEXT_DAY_VOUCHER: "voucher.view_next_day",
  DUPLICATE: "record.duplicate",
  ADD_ROW: "grid.add_row",
  DELETE_ROW: "grid.delete_row",
  QUICK_ADD_MASTER_DATA: "master.quick_add",
  SWITCH_TAB_OUTSIDE_LIST: "navigation.switch_tab_outside_list",
  SWITCH_TAB_IN_DETAIL: "navigation.switch_tab_in_detail",
  COPY_VALUES_DOWN: "grid.copy_values_down",
  QUICK_ITEM_SEARCH: "grid.quick_item_search",
  INPUT_DETAIL_BY_SPEC_CODE: "grid.input_detail_by_spec_code",
  VIEW_INVENTORY_BALANCE: "inventory.view_balance",
  SELECT_ISSUE_VOUCHER_SPECIFIC_IDENTIFICATION: "inventory.select_issue_voucher_specific_identification",
  VIEW_ACCOUNT_BALANCE: "account.view_balance",
  RECALCULATE_AMOUNT_BY_AFTER_TAX_PRICE: "grid.recalculate_amount_by_after_tax_price",
  CREATE_PURCHASE_FROM_EINVOICE: "voucher.create_purchase_from_einvoice",
  IMPORT: "grid.import",
  EXPORT_EXCEL: "grid.export_excel",
  EXPORT_PDF: "grid.export_pdf",
  COLUMN_CHOOSER: "grid.column_chooser",
  HELP: "system.help",
  CLOSE: "system.close",
  REFRESH: "system.refresh",
  FOCUS_MENU_SEARCH: "navigation.focus_menu_search",
} as const

export type ShortcutActionCode = (typeof SHORTCUT_ACTIONS)[keyof typeof SHORTCUT_ACTIONS]
export type ShortcutGroup = "system" | "form" | "grid" | "navigation"
export type ShortcutScope = "global" | "page" | "popup"

export type ShortcutDefinition = {
  action: ShortcutActionCode
  combo: ShortcutKeyCombo
  label: string
  labelKey?: string
  description?: string
  descriptionKey?: string
  group: ShortcutGroup
  scope: ShortcutScope
  icon?: string
  permissionKey?: string
  visible?: boolean
  allowInInput?: boolean
  commitActiveEditor?: boolean
  preventDefault?: boolean
  stopPropagation?: boolean
}

export const SHORTCUT_GROUP_ORDER: ShortcutGroup[] = ["system", "navigation", "form", "grid"]

export const SHARED_SHORTCUT_DEFINITIONS: Record<ShortcutActionCode, ShortcutDefinition> = {
  [SHORTCUT_ACTIONS.NEW_OR_ADD_RECEIPT]: {
    action: SHORTCUT_ACTIONS.NEW_OR_ADD_RECEIPT,
    combo: SHORTCUT_KEYS.NEW_OR_ADD_RECEIPT,
    label: "New / add receipt",
    labelKey: "RECEIPT_VOUCHER",
    description: "Create a new receipt voucher or jump to the receipt screen.",
    group: "navigation",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.ADD_PAYMENT]: {
    action: SHORTCUT_ACTIONS.ADD_PAYMENT,
    combo: SHORTCUT_KEYS.ADD_PAYMENT,
    label: "Add payment",
    labelKey: "PAYMENT_VOUCHER",
    description: "Create a new payment voucher or jump to the payment screen.",
    group: "navigation",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.OPEN]: {
    action: SHORTCUT_ACTIONS.OPEN,
    combo: SHORTCUT_KEYS.OPEN,
    label: "Open",
    labelKey: "Open",
    description: "Open the focused or selected record.",
    group: "grid",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.EDIT]: {
    action: SHORTCUT_ACTIONS.EDIT,
    combo: SHORTCUT_KEYS.EDIT,
    label: "Edit",
    labelKey: "lblEdit",
    description: "Edit the focused or selected record.",
    group: "grid",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.DELETE]: {
    action: SHORTCUT_ACTIONS.DELETE,
    combo: SHORTCUT_KEYS.DELETE,
    label: "Delete",
    labelKey: "MSG_BTNDELETE",
    description: "Delete the focused or selected record.",
    group: "grid",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.POST]: {
    action: SHORTCUT_ACTIONS.POST,
    combo: SHORTCUT_KEYS.POST,
    label: "Post / record",
    labelKey: "POST",
    description: "Post the selected voucher to the ledger.",
    group: "form",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.UNPOST]: {
    action: SHORTCUT_ACTIONS.UNPOST,
    combo: SHORTCUT_KEYS.UNPOST,
    label: "Unpost",
    labelKey: "UNPOST",
    description: "Undo posting for the selected voucher.",
    group: "form",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.QUICK_SEARCH]: {
    action: SHORTCUT_ACTIONS.QUICK_SEARCH,
    combo: SHORTCUT_KEYS.QUICK_SEARCH,
    label: "Quick search",
    labelKey: "Search...",
    description: "Focus the quick search box.",
    group: "navigation",
    scope: "page",
    allowInInput: true,
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.ADVANCED_VOUCHER_SEARCH]: {
    action: SHORTCUT_ACTIONS.ADVANCED_VOUCHER_SEARCH,
    combo: SHORTCUT_KEYS.ADVANCED_VOUCHER_SEARCH,
    label: "Advanced voucher search",
    labelKey: "MSG_BTNSER",
    description: "Focus voucher filter controls for advanced search.",
    group: "navigation",
    scope: "page",
    allowInInput: true,
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.SAVE]: {
    action: SHORTCUT_ACTIONS.SAVE,
    combo: SHORTCUT_KEYS.SAVE,
    label: "Save",
    labelKey: "TIT_SAVE",
    description: "Save the current document.",
    group: "form",
    scope: "popup",
    allowInInput: true,
    commitActiveEditor: true,
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.SAVE_AND_NEW]: {
    action: SHORTCUT_ACTIONS.SAVE_AND_NEW,
    combo: SHORTCUT_KEYS.SAVE_AND_NEW,
    label: "Save and new",
    labelKey: "SAVE_AND_NEW",
    description: "Save the current document and open a new one.",
    group: "form",
    scope: "popup",
    allowInInput: true,
    commitActiveEditor: true,
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.SAVE_AND_CLOSE]: {
    action: SHORTCUT_ACTIONS.SAVE_AND_CLOSE,
    combo: SHORTCUT_KEYS.SAVE_AND_CLOSE,
    label: "Save and close",
    labelKey: "SAVE_AND_CLOSE",
    description: "Save the current document and close the popup.",
    group: "form",
    scope: "popup",
    allowInInput: true,
    commitActiveEditor: true,
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.SAVE_AND_PRINT]: {
    action: SHORTCUT_ACTIONS.SAVE_AND_PRINT,
    combo: SHORTCUT_KEYS.SAVE_AND_PRINT,
    label: "Save and print",
    labelKey: "SAVE_AND_PRINT",
    description: "Save the current document and print it.",
    group: "form",
    scope: "popup",
    allowInInput: true,
    commitActiveEditor: true,
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.SAVE_AND_RELEASE]: {
    action: SHORTCUT_ACTIONS.SAVE_AND_RELEASE,
    combo: SHORTCUT_KEYS.SAVE_AND_RELEASE,
    label: "Save and release",
    labelKey: "SAVE_AND_RELEASE",
    description: "Save the current document and release it.",
    group: "form",
    scope: "popup",
    allowInInput: true,
    commitActiveEditor: true,
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.PRINT]: {
    action: SHORTCUT_ACTIONS.PRINT,
    combo: SHORTCUT_KEYS.PRINT,
    label: "Print",
    labelKey: "PRINT",
    description: "Print the current record or document.",
    group: "form",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.UTILITIES]: {
    action: SHORTCUT_ACTIONS.UTILITIES,
    combo: SHORTCUT_KEYS.UTILITIES,
    label: "Utilities",
    labelKey: "UTILITIES",
    description: "Open utility actions for the current screen.",
    group: "form",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.HOLD]: {
    action: SHORTCUT_ACTIONS.HOLD,
    combo: SHORTCUT_KEYS.HOLD,
    label: "Hold / cancel",
    labelKey: "HOLD",
    description: "Hold the current document or cancel the current action.",
    group: "form",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.VIEW_PREVIOUS_DAY_VOUCHER]: {
    action: SHORTCUT_ACTIONS.VIEW_PREVIOUS_DAY_VOUCHER,
    combo: SHORTCUT_KEYS.VIEW_PREVIOUS_DAY_VOUCHER,
    label: "Previous day voucher",
    labelKey: "VIEW_PREVIOUS_DAY_VOUCHER",
    description: "Move to vouchers from the previous day.",
    group: "navigation",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.VIEW_NEXT_DAY_VOUCHER]: {
    action: SHORTCUT_ACTIONS.VIEW_NEXT_DAY_VOUCHER,
    combo: SHORTCUT_KEYS.VIEW_NEXT_DAY_VOUCHER,
    label: "Next day voucher",
    labelKey: "VIEW_NEXT_DAY_VOUCHER",
    description: "Move to vouchers from the next day.",
    group: "navigation",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.DUPLICATE]: {
    action: SHORTCUT_ACTIONS.DUPLICATE,
    combo: SHORTCUT_KEYS.DUPLICATE,
    label: "Duplicate",
    labelKey: "btn_copy",
    description: "Duplicate the focused record or current document.",
    group: "grid",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.ADD_ROW]: {
    action: SHORTCUT_ACTIONS.ADD_ROW,
    combo: SHORTCUT_KEYS.ADD_ROW,
    label: "Add row",
    labelKey: "lblAddNew",
    description: "Add a new row or record.",
    group: "grid",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.DELETE_ROW]: {
    action: SHORTCUT_ACTIONS.DELETE_ROW,
    combo: SHORTCUT_KEYS.DELETE_ROW,
    label: "Delete selected rows",
    labelKey: "MSG_BTNDELETE",
    description: "Delete the current detail row.",
    group: "grid",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.QUICK_ADD_MASTER_DATA]: {
    action: SHORTCUT_ACTIONS.QUICK_ADD_MASTER_DATA,
    combo: SHORTCUT_KEYS.QUICK_ADD_MASTER_DATA,
    label: "Quick add master data",
    labelKey: "QUICK_ADD_MASTER_DATA",
    description: "Open quick add for master data.",
    group: "grid",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.SWITCH_TAB_OUTSIDE_LIST]: {
    action: SHORTCUT_ACTIONS.SWITCH_TAB_OUTSIDE_LIST,
    combo: SHORTCUT_KEYS.SWITCH_TAB_OUTSIDE_LIST,
    label: "Switch outer tab",
    labelKey: "SWITCH_TAB_OUTSIDE_LIST",
    description: "Switch focus to another outer tab.",
    group: "navigation",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.SWITCH_TAB_IN_DETAIL]: {
    action: SHORTCUT_ACTIONS.SWITCH_TAB_IN_DETAIL,
    combo: SHORTCUT_KEYS.SWITCH_TAB_IN_DETAIL,
    label: "Switch detail tab",
    labelKey: "SWITCH_TAB_IN_DETAIL",
    description: "Switch focus to another tab inside detail.",
    group: "navigation",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.COPY_VALUES_DOWN]: {
    action: SHORTCUT_ACTIONS.COPY_VALUES_DOWN,
    combo: SHORTCUT_KEYS.COPY_VALUES_DOWN,
    label: "Copy values down",
    labelKey: "COPY_VALUES_DOWN",
    description: "Copy values from the current row to rows below.",
    group: "grid",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.QUICK_ITEM_SEARCH]: {
    action: SHORTCUT_ACTIONS.QUICK_ITEM_SEARCH,
    combo: SHORTCUT_KEYS.QUICK_ITEM_SEARCH,
    label: "Quick item search",
    labelKey: "QUICK_ITEM_SEARCH",
    description: "Focus the detail item search box.",
    group: "grid",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.INPUT_DETAIL_BY_SPEC_CODE]: {
    action: SHORTCUT_ACTIONS.INPUT_DETAIL_BY_SPEC_CODE,
    combo: SHORTCUT_KEYS.INPUT_DETAIL_BY_SPEC_CODE,
    label: "Input by spec code",
    labelKey: "INPUT_DETAIL_BY_SPEC_CODE",
    description: "Input detail lines by specification code.",
    group: "grid",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.VIEW_INVENTORY_BALANCE]: {
    action: SHORTCUT_ACTIONS.VIEW_INVENTORY_BALANCE,
    combo: SHORTCUT_KEYS.VIEW_INVENTORY_BALANCE,
    label: "View inventory balance",
    labelKey: "VIEW_INVENTORY_BALANCE",
    description: "Open inventory balance information.",
    group: "grid",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.SELECT_ISSUE_VOUCHER_SPECIFIC_IDENTIFICATION]: {
    action: SHORTCUT_ACTIONS.SELECT_ISSUE_VOUCHER_SPECIFIC_IDENTIFICATION,
    combo: SHORTCUT_KEYS.SELECT_ISSUE_VOUCHER_SPECIFIC_IDENTIFICATION,
    label: "Select issue voucher",
    labelKey: "SELECT_ISSUE_VOUCHER_SPECIFIC_IDENTIFICATION",
    description: "Select issue vouchers for specific identification.",
    group: "grid",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.VIEW_ACCOUNT_BALANCE]: {
    action: SHORTCUT_ACTIONS.VIEW_ACCOUNT_BALANCE,
    combo: SHORTCUT_KEYS.VIEW_ACCOUNT_BALANCE,
    label: "View account balance",
    labelKey: "VIEW_ACCOUNT_BALANCE",
    description: "Open account balance information.",
    group: "grid",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.RECALCULATE_AMOUNT_BY_AFTER_TAX_PRICE]: {
    action: SHORTCUT_ACTIONS.RECALCULATE_AMOUNT_BY_AFTER_TAX_PRICE,
    combo: SHORTCUT_KEYS.RECALCULATE_AMOUNT_BY_AFTER_TAX_PRICE,
    label: "Recalculate amount",
    labelKey: "RECALCULATE_AMOUNT_BY_AFTER_TAX_PRICE",
    description: "Recalculate amount by after-tax unit price.",
    group: "grid",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.CREATE_PURCHASE_FROM_EINVOICE]: {
    action: SHORTCUT_ACTIONS.CREATE_PURCHASE_FROM_EINVOICE,
    combo: SHORTCUT_KEYS.CREATE_PURCHASE_FROM_EINVOICE,
    label: "Create purchase from e-invoice",
    labelKey: "CREATE_PURCHASE_FROM_EINVOICE",
    description: "Create a purchase document from an e-invoice.",
    group: "grid",
    scope: "popup",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.IMPORT]: {
    action: SHORTCUT_ACTIONS.IMPORT,
    combo: SHORTCUT_KEYS.IMPORT,
    label: "Import from Excel",
    labelKey: "MSG_BTNIMPORTEXCEL",
    description: "Import data from Excel.",
    group: "grid",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.EXPORT_EXCEL]: {
    action: SHORTCUT_ACTIONS.EXPORT_EXCEL,
    combo: SHORTCUT_KEYS.EXPORT_EXCEL,
    label: "Export Excel",
    labelKey: "MSG_BTNEXPORT",
    description: "Export data to Excel.",
    group: "grid",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.EXPORT_PDF]: {
    action: SHORTCUT_ACTIONS.EXPORT_PDF,
    combo: SHORTCUT_KEYS.EXPORT_PDF,
    label: "Export PDF",
    labelKey: "EXPORT_PDF_FILE",
    description: "Export data to PDF.",
    group: "grid",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.COLUMN_CHOOSER]: {
    action: SHORTCUT_ACTIONS.COLUMN_CHOOSER,
    combo: SHORTCUT_KEYS.COLUMN_CHOOSER,
    label: "Column chooser",
    labelKey: "AUDIT_SETTING_SHOW_HIDE",
    description: "Show or hide grid columns.",
    group: "grid",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.HELP]: {
    action: SHORTCUT_ACTIONS.HELP,
    combo: SHORTCUT_KEYS.HELP,
    label: "Shortcut help",
    labelKey: "SHORTCUT_HELP",
    description: "Open shortcut help.",
    group: "system",
    scope: "page",
    allowInInput: true,
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.CLOSE]: {
    action: SHORTCUT_ACTIONS.CLOSE,
    combo: SHORTCUT_KEYS.CLOSE,
    label: "Close",
    labelKey: "CANCEL",
    description: "Close the current popup or cancel editing.",
    group: "system",
    scope: "popup",
    allowInInput: true,
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.REFRESH]: {
    action: SHORTCUT_ACTIONS.REFRESH,
    combo: SHORTCUT_KEYS.REFRESH,
    label: "Refresh",
    labelKey: "MSG_BTNREFRESH",
    description: "Refresh the current screen.",
    group: "system",
    scope: "page",
    preventDefault: true,
  },
  [SHORTCUT_ACTIONS.FOCUS_MENU_SEARCH]: {
    action: SHORTCUT_ACTIONS.FOCUS_MENU_SEARCH,
    combo: SHORTCUT_KEYS.FOCUS_MENU_SEARCH,
    label: "Focus menu search",
    labelKey: "MENU_SEARCH",
    description: "Focus the main menu search box.",
    group: "navigation",
    scope: "global",
    allowInInput: true,
    preventDefault: true,
  },
}

export function translateShortcutDefinition(
  shortcut: ShortcutDefinition,
  translate: (key: string, fallback: string) => string,
): ShortcutDefinition {
  return {
    ...shortcut,
    label: shortcut.labelKey ? translate(shortcut.labelKey, shortcut.label) : shortcut.label,
    description: shortcut.descriptionKey
      ? translate(shortcut.descriptionKey, shortcut.description ?? "")
      : shortcut.description,
  }
}

export function getSharedShortcutDefinition(
  action: ShortcutActionCode,
  translate?: (key: string, fallback: string) => string,
) {
  const shortcut = SHARED_SHORTCUT_DEFINITIONS[action]
  return translate && shortcut ? translateShortcutDefinition(shortcut, translate) : shortcut
}

export function getSharedShortcutDefinitions(
  actions?: ShortcutActionCode[],
  translate?: (key: string, fallback: string) => string,
) {
  const items = actions?.length
    ? actions.map((action) => SHARED_SHORTCUT_DEFINITIONS[action]).filter(Boolean)
    : Object.values(SHARED_SHORTCUT_DEFINITIONS)

  const translated = translate
    ? items.map((item) => translateShortcutDefinition(item, translate))
    : items

  return [...translated].sort((left, right) => {
    const groupOrder =
      SHORTCUT_GROUP_ORDER.indexOf(left.group) - SHORTCUT_GROUP_ORDER.indexOf(right.group)
    if (groupOrder !== 0) {
      return groupOrder
    }

    return left.label.localeCompare(right.label)
  })
}
