import type { ColumnConfig } from "@/types/table"

export const companyColumns: ColumnConfig[] = [
  {
    id: "name",
    dataField: "name",
    displayName: "Tên công ty",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 0,
  },
  {
    id: "address",
    dataField: "address",
    displayName: "Địa chỉ",
    width: 250,
    visible: true,
    pinned: false,
    originalOrder: 1,
  },
  {
    id: "taxCode",
    dataField: "taxCode",
    displayName: "Mã số thuế",
    width: 140,
    visible: true,
    pinned: false,
    originalOrder: 2,
  },
  {
    id: "province",
    dataField: "province",
    displayName: "Tỉnh/TP",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 3,
  },
  {
    id: "taxOfficeCode",
    dataField: "taxOfficeCode",
    displayName: "Mã CQ Thuế",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 4,
  },
  {
    id: "phone",
    dataField: "phone",
    displayName: "SĐT",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 5,
  },
  {
    id: "email",
    dataField: "email",
    displayName: "Email",
    width: 180,
    visible: true,
    pinned: false,
    originalOrder: 6,
  },
  {
    id: "industry",
    dataField: "industry",
    displayName: "Ngành nghề",
    width: 180,
    visible: true,
    pinned: false,
    originalOrder: 7,
  },
]
