import type { ColumnConfig } from "@/types/table"

export const userColumns: ColumnConfig[] = [
  {
    id: "userId",
    dataField: "userId",
    displayName: "ID người dùng",
    width: 150,
    visible: true,
    pinned: false,
    originalOrder: 0,
  },
  {
    id: "name",
    dataField: "name",
    displayName: "Tên",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 1,
  },
  {
    id: "costCenterCode",
    dataField: "costCenterCode",
    displayName: "Đối tượng tập hợp chi phí",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 2,
  },
  {
    id: "permission",
    dataField: "permission",
    displayName: "Cho phép",
    width: 150,
    visible: true,
    pinned: false,
    originalOrder: 3,
  },
  {
    id: "phone",
    dataField: "phone",
    displayName: "Số điện thoại",
    width: 150,
    visible: true,
    pinned: false,
    originalOrder: 4,
  },
  {
    id: "issueDate",
    dataField: "issueDate",
    displayName: "Ngày cấp",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 5,
  },
  {
    id: "notes",
    dataField: "notes",
    displayName: "Ghi chú",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 6,
  },
  // Các cột ẩn
  {
    id: "lockOption",
    dataField: "lockOption",
    displayName: "Lựa chọn khóa",
    width: 150,
    visible: false,
    pinned: false,
    originalOrder: 8,
  },
  {
    id: "cannotDeleteLinked",
    dataField: "cannotDeleteLinked",
    displayName: "Không thể xóa chứng từ đã liên kết",
    width: 200,
    visible: false,
    pinned: false,
    originalOrder: 9,
  },
  {
    id: "cannotEditLocked",
    dataField: "cannotEditLocked",
    displayName: "Không thể sửa chứng từ đã khóa sổ",
    width: 200,
    visible: false,
    pinned: false,
    originalOrder: 10,
  },
  {
    id: "cannotAddLock",
    dataField: "cannotAddLock",
    displayName: "Không thể thêm khóa sổ",
    width: 180,
    visible: false,
    pinned: false,
    originalOrder: 11,
  },
  {
    id: "editReservedName",
    dataField: "editReservedName",
    displayName: "Sửa chữ dành/Tên",
    width: 150,
    visible: false,
    pinned: false,
    originalOrder: 12,
  },
  {
    id: "showDocumentsByUser",
    dataField: "showDocumentsByUser",
    displayName: "Hiện thị chứng từ theo người đăng nhập",
    width: 250,
    visible: false,
    pinned: false,
    originalOrder: 13,
  },
]