import type { ColumnConfig } from "@/types/table"

export const khoColumns: ColumnConfig[] = [
  {
    id: "productCode",
    dataField: "PRODUCT_CD",
    displayName: "Mã sản phẩm",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 0,
  },
  {
    id: "divisionCode",
    dataField: "DivisionCD",
    displayName: "Mã bộ phận",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 1,
  },
  {
    id: "productKindCode",
    dataField: "PRODUCTKIND_CD",
    displayName: "Mã loại sản phẩm",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 2,
  },
  {
    id: "departmentCode",
    dataField: "DepartmentCD",
    displayName: "Mã phòng ban",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 3,
  },
  {
    id: "productNameVi",
    dataField: "PRODUCT_NM",
    displayName: "Tên sản phẩm (VI)",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 4,
  },
  {
    id: "productNameEng",
    dataField: "PRODUCT_NM_ENG",
    displayName: "Tên sản phẩm (EN)",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 5,
  },
  {
    id: "productNameKor",
    dataField: "PRODUCT_NM_KOR",
    displayName: "Tên sản phẩm (KO)",
    width: 200,
    visible: true,
    pinned: false,
    originalOrder: 6,
  },
  {
    id: "inboundUnitCode",
    dataField: "InboundUnitCD",
    displayName: "Đơn vị nhập kho",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 7,
  },
  {
    id: "outboundUnitCode",
    dataField: "OutboundUnitCD",
    displayName: "Đơn vị xuất kho",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 8,
  },
  {
    id: "materialInputUnitCode",
    dataField: "materialInputUnitCD",
    displayName: "Đơn vị nhập NVL",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 9,
  },
  {
    id: "stockUnitCode",
    dataField: "StockUnitCD",
    displayName: "Đơn vị tồn kho",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 10,
  },
  {
    id: "inboundQuantity",
    dataField: "InboundQuantity",
    displayName: "Số lượng nhập kho",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 11,
  },
  {
    id: "outboundQuantity",
    dataField: "OutboundQuantity",
    displayName: "Số lượng xuất kho",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 12,
  },
  {
    id: "materialInputQuantity",
    dataField: "MaterialInputQuantity",
    displayName: "Số lượng nhập NVL",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 13,
  },
  {
    id: "storeCode",
    dataField: "StoreCD",
    displayName: "Mã kho lưu trữ",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 14,
  },
  {
    id: "standardCode",
    dataField: "StandardCD",
    displayName: "Mã tiêu chuẩn",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 15,
  },
  {
    id: "fitnessStock",
    dataField: "FitnessStock",
    displayName: "Tồn kho khả dụng",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 16,
  },
  {
    id: "unitPrice",
    dataField: "UnitPrice",
    displayName: "Đơn giá",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 17,
  },
  {
    id: "fcUnitPrice",
    dataField: "FcUnitPirce",
    displayName: "Đơn giá ngoại tệ",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 18,
  },
  {
    id: "exchangeRate",
    dataField: "ExRate",
    displayName: "Tỷ giá",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 19,
  },
  {
    id: "lblCCType",
    dataField: "lblCCType",
    displayName: "Loại CC",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 20,
  },
  {
    id: "lblFCType",
    dataField: "lblFCType",
    displayName: "Loại ngoại tệ",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 21,
  },
  {
    id: "summary",
    dataField: "txtSummary",
    displayName: "Ghi chú",
    width: 250,
    visible: true,
    pinned: false,
    originalOrder: 22,
  },
  {
    id: "useNotUse",
    dataField: "rgUseNotUse",
    displayName: "Sử dụng/Không sử dụng",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 23,
  },
  {
    id: "haveChildBOM",
    dataField: "HaveChildBOM",
    displayName: "Có BOM con",
    width: 120,
    visible: true,
    pinned: false,
    originalOrder: 24,
  },
  {
    id: "origin",
    dataField: "Origin",
    displayName: "Xuất xứ",
    width: 150,
    visible: true,
    pinned: false,
    originalOrder: 25,
  },
]
